# Workflow para desplegar la aplicación de angular

name: runAngular

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: seminarioEA   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14'                # set this to the node version to use


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Descarga nuestro repositorio y lo monta en la maquina virtual
      - name: Checkout
        uses: actions/checkout@v2
     # instala node v14 en la maquina virtual   
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      #instala dependencias
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build:ci
      
        
      #Cargar artefactos de compilacion
      - name: Archive build
        if: success() #Solo se crea si todos los pasos anteriores son correctos
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
      
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


