# Workflow para desplegar la aplicación de angular

name: runAngular

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Descarga nuestro repositorio y lo monta en la maquina virtual
      - name: Checkout
        uses: actions/checkout@v2
     # instala node v14 en la maquina virtual   
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      #instala dependencias
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build:ci
      
      - name: Test
        run: npm run test:ci
        
      #Cargar artefactos de compilacion
      - name: Archive build
        if: success() #Solo se crea si todos los pasos anteriores son correctos
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
          
      #Cargar artefactos de cobertura del codigo
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: coverage
          
  #Crear el trabajo de implementacion
  deploy:
    runs-on: ubuntu-latest
    needs: build #Solamente se implementara si ha acabado correctamente el build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build #implementa el artefacto1
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/angular-demo
